config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # devise_for :users
  root to: 'pages#landing'
  get "/home" => "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :projects, :resources
  #get 'resources/:discipline', to: 'resources#show'

  get "/contact" => "pages#contact"
  # get "/resources" => "pages#resources"
  get "/beta" => "pages#beta"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resource.rb
class Resource < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home, :projects]

  def home
  end

  def contact
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    #
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController

  def fetchMe(url)
    jsonData = LinkThumbnailer.generate(url).to_json
    hashData = JSON.parse(jsonData)
    if hashData['favicon'].match(/^http?(.*)/)
      avatar = hashData['favicon']
    else
    avatar = url + hashData['favicon']
  end
    finalData = {url: hashData['url'], description: hashData['description'], title: hashData['title'], avatar: avatar}
  end

  def index
    @resources = Resource.all
    # @data = fetchMe('https://stackoverflow.com/questions')
  end

  def new
    #if user_signed_in? && current_user.email == "contact@gheorghetarcea.com"
      @resource = Resource.new
    #end
  end

  def show
    @resource = Resource.find(params[:id])
    # raise
  end

  def create
    data = fetchMe(params[:resource]["url"])
    data[:discipline] = params[:resource]["discipline"]
    @resource = Resource.new(data)
    if @resource.save
      redirect_to resources_path, notice: 'created OK'
    else
      render :new
    end
  end

  def edit
    @resource = Resource.find(params[:id])
  end

  def update
    @resource = Resource.find(params[:id])
    @resource.update(resource_params)
    redirect_to resources_path, notice: 'update done'
  end

  def destroy
    @resource = Resource.find(params[:id])
    @resource.destroy
    redirect_to resources_path
    end

  private

  def resource_params
    params.require(:resource).permit(:url, :title, :description, :discipline, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('icons8-sun-480.png') %>
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> -->
    <title>Web development | Gheorghe Tarcea</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="robots" content="index, follow">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="Ruby, Rails, Web development, HTML, CSS, JavaScript">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="Web development for beautiful people and smart businesses">

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/konpa/devicon@master/devicon.min.css">
    <%= javascript_pack_tag 'hello_react' %>
  </head>
  <body>
  <div class="container">
    <!-- <%= render 'shared/navbar_hover' %> -->
    <%= render 'shared/navbar_bootstrap' unless current_page?(root_path) %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer' unless current_page?(root_path) %>
</div>
  </body>
</html>

app/views/pages/_home.html.erb
<!-- this is just a temporary file -->
<div class="container">
  <div class="card-white">
    <h2>Gheorghe Tarcea</h2>
    <ul class="list-inline">
      <li>
        <a href="mailto:contact@gheorghetarcea.com" target="_blank">
             contact@gheorghetarcea.com
        </a>
      </li>
      <li>
        <a href="https://www.facebook.com/gheorghe.tarcea" target="_blank">
          <i class="fab fa-facebook-square"></i>
        </a>
      </li>
      <li>
        <a href="https://github.com/tarcea" target="_blank">
          <i class="fab fa-github-square"></i>
        </a>
      </li>
      <li>
        <a href="https://www.instagram.com/ghtarcea/" target="_blank">
          <i class="fab fa-instagram"></i>
        </a>
      </li>
      <li>
        <a href="https://www.linkedin.com/in/gheorghe-tarcea-0a2b4589" target="_blank">
          <i class="fab fa-linkedin"></i>
        </a>
      </li>
      <li>
        <a href="http://www.gheorghetarcea.com" target="_blank">
           http://www.gheorghetarcea.com
        </a>
      </li>
      </ul>
       <p>Page under construction ....</p>
    </div>
 <div class="row row-cols-1 row-cols-md-2">
  <div class="col mb-4">
    <div class="card">
      <img src="<%= asset_path('fantanele1.jpg') %>" class="card-img-top" alt="unu">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card">
      <img src="<%= asset_path('fantanele1.jpg') %>" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card">
      <img src="<%= asset_path('fantanele1.jpg') %>" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content.</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card">
      <img src="<%= asset_path('fantanele1.jpg') %>" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
</div>
</div>

app/views/pages/beta.html.erb
<!-- <div class="container"> -->
  <div class="card-white text-center" style="position: relative;">
    <div class="d-flex justify-content-around">
      <%= octicon "alert", :height => 99 %>
      <p style="position: absolute; top: 12px;">Under construction</p>
    </div>
  </div>
<!-- </div> -->

app/views/pages/contact.html.erb
<!-- <div class="container"> -->

    <div class="card-white text-center" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1484191914255-a429e6f819b4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2550&q=80); background-size: cover;">
      <h1>Contact</h1>
    </div>

    <div class="card-white text-center">
      <div class="d-flex justify-content-around contact">
        <a href="https://github.com/tarcea/" target="_blank"><i class="fab fa-github"></i></a>
        <a href="https://www.instagram.com/ghtarcea/" target="_blank"><i class="fab fa-instagram"></i></a>
        <a href="https://www.facebook.com/gheorghe.tarcea" target="_blank"><i class="fab fa-facebook"></i></a>
        <a href="https://twitter.com/GheorgheTarcea" target="_blank"><i class="fab fa-twitter"></i></a>
        <a href="https://www.linkedin.com/in/gheorghe-tarcea-0a2b4589" target="_blank"><i class="fab fa-linkedin"></i></a>
        <a href="mailto:contact@gheorghetarcea.com" target="_blank"><i class="fas fa-envelope-square"></i></a>
      </div>
    </div>

    <div class="card-white text-center">
        <h6>0046704024031 <i class="fas fa-phone"></i></h6>
        <div class="d-flex justify-content-around contact">
        <i class="devicon-ruby-plain"></i>
        <i class="devicon-rails-plain"></i>
        <i class="devicon-postgresql-plain"></i>
        <i class="devicon-javascript-plain"></i>
        <i class="devicon-react-original"></i>
        <i class="devicon-heroku-original"></i>
        <i class="devicon-bootstrap-plain"></i>
        <i class="devicon-html5-plain"></i>
        <i class="devicon-css3-plain"></i>
        <i class="devicon-github-plain"></i>
        <i class="devicon-trello-plain"></i>
        </div>
        <h6>gheorghe.tarcea <i class="fab fa-skype"></i></h6>
      </div>
    <!-- </div> -->

app/views/pages/home.html.erb
<!-- <div class="container"> -->
<!-- <div class="row justify-content-center"> -->
<div class="card-white text-center">
<hr>
    <h6>Web development for beautiful people and smart businesses</h6>
<hr>
  <div class="icons">
      <i class="devicon-ruby-plain"></i>
      <i class="devicon-rails-plain"></i>
      <i class="devicon-postgresql-plain"></i>
      <i class="devicon-javascript-plain"></i>
      <i class="devicon-react-original"></i>
      <i class="devicon-heroku-original"></i>
      <i class="devicon-bootstrap-plain"></i>
      <i class="devicon-html5-plain"></i>
      <i class="devicon-css3-plain"></i>
      <i class="devicon-git-plain"></i>
      <i class="devicon-github-plain"></i>
      <i class="devicon-slack-plain"></i>
      <i class="devicon-trello-plain"></i>
    </div>
  <div class="row justify-content-center">
    <h6><span id="effect"></span></h6>
  </div>

<div class="card-white">
  <div class="row justify-content-center">
    <img src="<%= asset_path('fantanele1.jpg') %>" alt="" style="max-width:100%; max-height:100%;">
  </div>
</div>
 <!--  <figure class="hover-menu">
    <img src="<%= asset_path('fantanele1_marked.jpg') %>" />
    <div>
      <a href="https://github.com/tarcea" target="_blank"><i class="fab fa-github"></i></a>
      <a href="https://www.instagram.com/ghtarcea/" target="_blank"><i class="fab fa-instagram"></i></a>
      <a href="https://www.facebook.com/gheorghe.tarcea" target="_blank"><i class="fab fa-facebook"></i></a>
      <a href="https://twitter.com/GheorgheTarcea" target="_blank"><i class="fab fa-twitter"></i></a>
      <a href="https://www.linkedin.com/in/gheorghe-tarcea-0a2b4589" target="_blank"><i class="fab fa-linkedin"></i></a>
      <a href="mailto:contact@gheorghetarcea.com" target="_blank"><i class="fas fa-envelope-square"></i></a>
    </div>
  </figure> -->

  <!-- <h1>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem quisquam ea officia dicta, totam cupiditate aspernatur, repellendus veniam dolorum rem eveniet. Voluptatem vero et animi quisquam officia distinctio similique unde!</h1> -->
  <!-- <div class="row">
    <p>RoR development for <span id="effect"></span></p>
  </div> -->
<div class="card-white">
  <div class="row justify-content-center">
    <h6>contact@gheorghetarcea.com<br>
      0046704024031
    </h6>
  </div>
</div>

</div>
<!-- </div> -->
<!-- </div> -->

app/views/pages/landing.html.erb
<body class="landing">
    <div class="row d-flex flex-column justify-content-center">
  <div class="main-text text-center"><h1> Hi, I'm the <mark>web developer</mark> you may need, check this out... </h1></div>
      <div class="container justify-content-center col-12">
        <hr>
        <small class="skills"> P R O J E C T S </small>
        <hr>
        <div class="row">
          <div class="col-sm-6">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Travel Worms</h5>
                <p class="card-text">Ruby on Rails project developed in 2 weeks in a team of four.</p>
                <a href="https://travel-worms.herokuapp.com/" class="btn" target="new">Go and see it</a>
              </div>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Rent a Pet</h5>
                <p class="card-text">Ruby on Rails project developed in 1 week in a team of four.</p>
                <a href="https://stockholm376-rent-a-pet.herokuapp.com/" class="btn" target="new">Go and see it</a>
              </div>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Profile</h5>
                <p class="card-text">My first profile page, HTML, CSS, Bootstrap project.</p>
                <a href="https://tarcea.github.io/profile/" class="btn" target="new">Go and see it</a>
              </div>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Fancy profile</h5>
                <p class="card-text">Another profile page, Ruby on Rails, JS, React, Bootstrap ....</p>
                <a href="http://www.gheorghetarcea.com/home/" class="btn" target="new">Go and see it</a>
              </div>
            </div>
          </div>
        </div>
        <hr>
        <!-- <div class="row justify-content-center"> -->
          <small class="skills"> S K I L L S </small>
          <hr>
        <ul class="list-group">
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Ruby on Rails
            <span class="badge badge-primary badge-pill">good</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            PostgreSQL
            <span class="badge badge-primary badge-pill">good</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            MongoDB
            <span class="badge badge-primary badge-pill">beginner</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            JavaScript, NodeJS
            <span class="badge badge-primary badge-pill">beginner</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            React
            <span class="badge badge-primary badge-pill">beginner</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Heroku
            <span class="badge badge-primary badge-pill">good</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Bootstrap
            <span class="badge badge-primary badge-pill">good</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            HTML, CSS
            <span class="badge badge-primary badge-pill">good</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Git, Github
            <span class="badge badge-primary badge-pill">good</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Slack, Trello
            <span class="badge badge-primary badge-pill">good</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Figma
            <span class="badge badge-primary badge-pill">good</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Python
            <span class="badge badge-primary badge-pill">beginner</span>
          </li>
        </ul>
        <!-- </div> -->
        <hr>
        <small class="skills"> C O N T A C T </small>
        <hr>
        <p>Gheorghe Tarcea</p>
        <p><i class="fas fa-phone"></i> 0046704024031 </p>
        <p><i class="fas fa-envelope-square"></i> tarcea@gmail.com </p>
        <p><%= link_to 'Open', 'G.Tarcea.pdf', open: 'G.Tarcea_resume.pdf', class: "btn btn-sm"  %> My Resume <%= link_to 'Download', 'G.Tarcea.pdf', download: 'G.Tarcea_resume.pdf', class: "btn btn-sm"  %></p>


      </div>

      <%= link_to "If you want more ...", home_path, class: "btn" %>
    </div>
</body>

app/views/pages/resources.html.erb
<!-- <div class="container"> -->

    <div class="card-white text-center" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1518933165971-611dbc9c412d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2689&q=80); background-size: cover;">
      <h1>Resources</h1>
    </div>

    <div class="card-white text-center" style="position: relative;">
      <div class="d-flex justify-content-around">
        <%= octicon "alert", :height => 99 %>
        <p style="position: absolute; top: 12px;">Under construction</p>
      </div>
    </div>

    <div class="card-white text-center">
      <i class="devicon-ruby-plain"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-rails-plain"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-postgresql-plain"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-javascript-plain"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-react-original"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-heroku-original"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-bootstrap-plain"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-html5-plain"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-css3-plain"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-github-plain"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-trello-plain"></i>
    </div>

    <div class="card-white text-center">
       <i class="devicon-git-plain"></i>
    </div>

<!-- </div> -->

app/views/resources/_edit.html.erb
<%= simple_form_for @resource do |f| %>
  <!-- <%= f.input :url %> -->
  <%= f.input :title %>
  <%= f.input :description %>
  <!-- <%= f.input :avatar %> -->
  <%= f.select :discipline, ["Ruby on Rails", "PostgreSQL", "Mongo DB", "Java script", "NodeJS", "React", "Heroku", "Bootstrap",
            "HTML", "CSS", "Git", "Github", "Slack", "Trello",
            "Figma", "General Topic", "Q & A"], class: 'form-control' %>
  <%= f.button :submit, class: 'btn' %>
<% end %>

app/views/resources/_form.html.erb
<%= simple_form_for @resource do |f| %>
  <%= f.input :url %>
  <!-- <%= f.input :description %> -->
  <%= f.select :discipline, ["Ruby on Rails", "PostgreSQL", "Mongo DB", "Java script", "NodeJS", "React", "Heroku", "Bootstrap",
            "HTML", "CSS", "Git", "Github", "Slack", "Trello",
            "Figma", "General Topic", "Q & A"], class: 'form-control' %>
  <%= f.button :submit, class: 'btn' %>
<% end %>

app/views/resources/edit.html.erb
<% if user_signed_in? && current_user.email == "contact@gheorghetarcea.com" %>
<div class="container">
<!--   <div class="border-top"> -->
    <div class="row justify-content-center">
      <div class="col-sm-10 col-md-8 col-lg-6">
        <h4>Edit <%= @resource.url %></h4>
        <%= render 'edit', resource: @resource %>
      </div>
    </div>
<!--   </div> -->
</div>
<% end %>

app/views/resources/index.html.erb
<div class="card-white text-center" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1518933165971-611dbc9c412d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2689&q=80); background-size: cover;">
      <h1>Resources</h1>
</div>
<div class="landing">
<div class="row d-flex flex-column justify-content-center">
  <div class="container justify-content-center col-12">
    <% if user_signed_in? && current_user.email == "contact@gheorghetarcea.com" %>
    <%= link_to "Add resource", new_resource_path, class: "btn btn-block" %>
    <% end %>
    <div class="row">
      <% @resources.reverse.each do |resource| %>
      <div class="col-sm-6 margin-box">
        <div class="card h-100">
          <div class="card-body">
            <h5 class="card-title"><%= resource.title %></h5>
            <img src="<%= resource.avatar %>", height="80", width="80", alt="">
            <!-- <p class="card-text"><%= resource.description %></p> -->
            <p class="card-text"><%= resource.description %></p>
            <%= link_to 'Go there', resource.url, class: 'btn float-go', target: 'new' %>
            <% if user_signed_in? && current_user.email == "contact@gheorghetarcea.com" %>
            <div class="ics">
            <%= link_to (octicon "x", :height => 24), resource_path(resource), method: :delete, data: { confirm: 'Are you sure?', class: "delete-button" } %>
            </div>
            <%= link_to 'Edit', edit_resource_path(resource), class: 'btn float-edit' %>
            <% end %>
            <p class="discipline"><%= resource.discipline %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <% if user_signed_in? && current_user.email == "contact@gheorghetarcea.com" %>
    <%= link_to "Add resource", new_resource_path, class: "btn btn-block mt" %>
    <% end %>
  </div>
</div>

<!--
<% @resources.each do |resource| %>
<% obj = LinkThumbnailer.generate(resource.url) %>

<% obj.images.each do |image| %>
<% unless image.nil? %>
images: <img src="<%= image.src.to_s %>" alt="">  <br>
<% end %>
<% end %>

title: <%= obj.title %> <br>
favicon: <img src="<%= obj.url + obj.favicon %>" alt="">  <br>
description: <%= obj.description %> <br>
discipline: <%= resource.discipline %> <br>
<% end %>
-->



<!--
    <div class="card-white text-center" style="position: relative;">
      <div class="d-flex justify-content-around">
        <%= octicon "alert", :height => 99 %>
        <p style="position: absolute; top: 12px;">Under construction</p>
      </div>
    </div>

    <div class="card-white text-center">
      <i class="devicon-ruby-plain"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-rails-plain"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-postgresql-plain"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-javascript-plain"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-react-original"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-heroku-original"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-bootstrap-plain"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-html5-plain"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-css3-plain"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-github-plain"></i>
    </div>

    <div class="card-white text-center">
      <i class="devicon-trello-plain"></i>
    </div>

    <div class="card-white text-center">
       <i class="devicon-git-plain"></i>
    </div>



-->
</div>

app/views/shared/_navbar_bootstrap.html.erb
<!-- <div class="container"> -->
  <% if user_signed_in? && current_user.email == "contact@gheorghetarcea.com" %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <%= link_to current_user.email, home_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active"><%= link_to "Home", home_path, class: "nav-link" %><span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link"><%= link_to "Projects", projects_path, class: "nav-link" %></a>
      <a class="nav-item nav-link"><%= link_to "Resources", resources_path, class: "nav-link" %></a>
      <a class="nav-item nav-link"><%= link_to "Beta", beta_path, class: "nav-link" %></a>
      <a class="nav-item nav-link"><%= link_to "Contact", contact_path, class: "nav-link" %></a>
      <a class="nav-item nav-link"><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %></a>
      <!-- <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> -->
    </div>
  </div>
</nav>
  <% else %>
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <%= link_to "Gheorghe Tarcea", home_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active"><%= link_to "Home", home_path, class: "nav-link" %><span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link"><%= link_to "Projects", projects_path, class: "nav-link" %></a>
      <a class="nav-item nav-link"><%= link_to "Resources", resources_path, class: "nav-link" %></a>
      <a class="nav-item nav-link"><%= link_to "Beta", beta_path, class: "nav-link" %></a>
      <a class="nav-item nav-link"><%= link_to "Contact", contact_path, class: "nav-link" %></a>
      <!-- <a class="nav-item nav-link"><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %></a> -->
      <!-- <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> -->
    </div>
  </div>
</nav>
<% end %>
<!-- </div> -->

app/views/shared/_navbar_hover.html.erb
<div class="row justify-content-center">
  <nav class="hover-nav">
    <ul>
        <li><%= link_to "Home", root_path, class: "nav-link" %></li>
        <li><%= link_to "Projects", projects_path, class: "nav-link" %></li>
        <li><%= link_to "Resources", resources_path, class: "nav-link" %></li>
        <li><%= link_to "Beta", beta_path, class: "nav-link" %></li>
        <li><%= link_to "Contact", contact_path, class: "nav-link" %></li>
    </ul>
  </nav>
</div>